# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('inicial', models.IntegerField()),
                ('ingreso', models.IntegerField()),
                ('final', models.IntegerField()),
                ('salida', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('fecha', models.DateField()),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendedor.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ManyToManyField(blank=True, to='inventario.Producto'),
        ),
    ]
