# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='fecha',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='final',
            new_name='InventarioFinal',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='inicial',
            new_name='InventarioInicial',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='persona',
            new_name='Persona',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='producto',
            new_name='Producto',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='salida',
            new_name='Salida',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='valor',
            new_name='Valor',
        ),
    ]
